const cards = [
  // Major Arcana
  {"id":"00","name":"The Fool","type":"Major Arcana","image":"images/cards/00.png","message":"A day full of surprises and spontaneity awaits you.","meaning":"Take a leap of faith and trust the universe. New beginnings are highlighted today. Stay open to unexpected opportunities. Avoid overthinking. Embrace adventure and curiosity. Keep your heart light and playful."},
  {"id":"01","name":"The Magician","type":"Major Arcana","image":"images/cards/01.png","message":"Your skills are at their peak—act with confidence.","meaning":"Focus your energy on manifesting your desires. Tools and resources are aligned. Trust your abilities. Be proactive in communication and actions. Creativity and initiative bring success. Today you have the power to shape outcomes."},
  {"id":"02","name":"The High Priestess","type":"Major Arcana","image":"images/cards/02.png","message":"Secrets may reveal themselves—trust your intuition.","meaning":"Inner guidance is strong. Pay attention to dreams and signs. Quiet reflection brings clarity. Avoid impulsive decisions. Intuition will guide you toward hidden truths. Meditation and observation enhance understanding."},
  {"id":"03","name":"The Empress","type":"Major Arcana","image":"images/cards/03.png","message":"Abundance surrounds you—nurture creativity and growth.","meaning":"Embrace creativity and nurturing energy. Focus on home, family, and comfort. Nature and beauty inspire you. Generosity and compassion bring rewards. Patience yields fruitful outcomes. Your environment supports growth."},
  {"id":"04","name":"The Emperor","type":"Major Arcana","image":"images/cards/04.png","message":"Structure and stability are in your favor today.","meaning":"Take charge with confidence. Leadership and authority guide decisions. Rules and order help achieve goals. Discipline strengthens your position. Plan strategically for long-term success. Responsibility brings respect."},
  {"id":"05","name":"The Hierophant","type":"Major Arcana","image":"images/cards/05.png","message":"Tradition and guidance offer insight.","meaning":"Seek advice from mentors. Follow established paths where appropriate. Spiritual or moral guidance illuminates choices. Learning from institutions or elders helps. Shared beliefs create community. Stay aligned with your values."},
  {"id":"06","name":"The Lovers","type":"Major Arcana","image":"images/cards/06.png","message":"Choices from the heart influence your day.","meaning":"Relationships and emotional connections are highlighted. Make decisions with care and honesty. Harmony and balance guide interactions. Romantic opportunities may appear. Align actions with personal values. Love and communication flourish."},
  {"id":"07","name":"The Chariot","type":"Major Arcana","image":"images/cards/07.png","message":"Determination propels you forward.","meaning":"Focus on goals with discipline and drive. Obstacles can be overcome with willpower. Stay confident and assertive. Balance opposing forces for success. Movement and travel may occur. Achieve victory through focus and control."},
  {"id":"08","name":"Strength","type":"Major Arcana","image":"images/cards/08.png","message":"Inner courage guides you today.","meaning":"Face challenges with compassion and patience. Physical and mental strength are highlighted. Self-control and resilience aid decisions. Tame fears with gentle resolve. Confidence grows through action. Empathy strengthens relationships."},
  {"id":"09","name":"The Hermit","type":"Major Arcana","image":"images/cards/09.png","message":"Reflection leads to clarity and insight.","meaning":"Seek solitude to understand your path. Inner guidance illuminates choices. Avoid distractions and external noise. Meditation and contemplation are valuable. Wisdom grows from introspection. Take time to recharge and reflect."},
  {"id":"10","name":"Wheel of Fortune","type":"Major Arcana","image":"images/cards/10.png","message":"Change is in the air—embrace cycles.","meaning":"Life shifts unpredictably. Be open to new opportunities. Luck may favor unexpected directions. Adaptability brings success. Understand cause and effect. Embrace the flow of life."},
  {"id":"11","name":"Justice","type":"Major Arcana","image":"images/cards/11.png","message":"Fairness and balance guide your choices.","meaning":"Act with honesty and integrity. Decisions have long-term consequences. Seek truth in all matters. Legal or moral issues may arise. Equilibrium is essential. Stay accountable for your actions."},
  {"id":"12","name":"The Hanged Man","type":"Major Arcana","image":"images/cards/12.png","message":"Pause and see things from a new perspective.","meaning":"Let go of old patterns. Reflection brings insight. Sacrifice may be necessary. Accept situations beyond control. Patience reveals clarity. New understanding emerges."},
  {"id":"13","name":"Death","type":"Major Arcana","image":"images/cards/13.png","message":"Endings bring transformation and renewal.","meaning":"A phase is ending to allow growth. Embrace change rather than resist. Let go of attachments. Transformation leads to new opportunities. Accept transitions gracefully. Renewal is possible through closure."},
  {"id":"14","name":"Temperance","type":"Major Arcana","image":"images/cards/14.png","message":"Balance and moderation guide you.","meaning":"Seek harmony in all areas. Avoid extremes. Combine different energies for optimal results. Patience brings rewards. Emotional and physical balance is key. Integration leads to stability."},
  {"id":"15","name":"The Devil","type":"Major Arcana","image":"images/cards/15.png","message":"Awareness of attachments is important today.","meaning":"Examine areas of restriction or temptation. Avoid unhealthy patterns. Recognize power dynamics and control issues. Free yourself from limiting beliefs. Focus on personal empowerment. Take responsibility for choices."},
  {"id":"16","name":"The Tower","type":"Major Arcana","image":"images/cards/16.png","message":"Sudden change shakes foundations—adapt quickly.","meaning":"Expect disruption and unexpected events. Old structures may collapse. Embrace transformation. Learn from upheaval. Flexibility ensures resilience. Opportunities arise from challenges."},
  {"id":"17","name":"The Star","type":"Major Arcana","image":"images/cards/17.png","message":"Hope and inspiration light your path.","meaning":"Renewed optimism guides actions. Creativity and spirituality flourish. Healing is possible. Align with dreams and visions. Guidance from the universe is strong. Stay hopeful and inspired."},
  {"id":"18","name":"The Moon","type":"Major Arcana","image":"images/cards/18.png","message":"Intuition and subtle messages are key today.","meaning":"Be aware of illusions and hidden factors. Trust intuition over appearances. Emotional awareness is heightened. Dreams carry messages. Navigate uncertainty with caution. Reflection reveals truths."},
  {"id":"19","name":"The Sun","type":"Major Arcana","image":"images/cards/19.png","message":"Joy and success brighten your day.","meaning":"Positive energy surrounds you. Achievements are recognized. Happiness and vitality are highlighted. Relationships thrive. Creativity and playfulness flourish. Express gratitude for abundance."},
  {"id":"20","name":"Judgement","type":"Major Arcana","image":"images/cards/20.png","message":"Awakening and self-reflection guide you.","meaning":"Evaluate past actions with honesty. Renewal and rebirth are possible. Make conscious choices. Forgiveness and understanding are powerful. Embrace lessons learned. Transformation is imminent."},
  {"id":"21","name":"The World","type":"Major Arcana","image":"images/cards/21.png","message":"Completion and fulfillment mark your day.","meaning":"Celebrate accomplishments. Recognize cycles completed. Harmony and balance are present. Success brings confidence. Travel or achievement may occur. Embrace wholeness and unity."},

  // Minor Arcana - Pentacles
  {"id":"p01","name":"Ace of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p01.png","message":"New material opportunities arise.","meaning":"A financial or career opportunity appears. Focus on practical steps. Stay grounded in decisions. Long-term rewards possible. Generosity may return value. Seize the chance to grow."},
  {"id":"p02","name":"Two of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p02.png","message":"Balance is key today.","meaning":"Juggle priorities carefully. Adapt to changing circumstances. Manage resources wisely. Flexibility ensures success. Avoid overcommitment. Focus on organization and planning."},
  {"id":"p03","name":"Three of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p03.png","message":"Collaboration brings progress.","meaning":"Work with others harmoniously. Team efforts succeed. Recognize skills of peers. Build on shared goals. Communicate effectively. Learn from collaboration."},
  {"id":"p04","name":"Four of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p04.png","message":"Hold onto resources wisely.","meaning":"Be mindful of finances. Avoid being overly possessive. Protect assets without fear. Plan for future stability. Balance generosity and saving. Security is achievable."},
  {"id":"p05","name":"Five of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p05.png","message":"Challenges may arise in material matters.","meaning":"Financial or health difficulties may appear. Seek support if needed. Stay resourceful and resilient. Avoid despair. Learn from hardships. Persevere through temporary setbacks."},
  {"id":"p06","name":"Six of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p06.png","message":"Generosity brings balance.","meaning":"Give and receive support. Sharing resources enhances relationships. Practice fairness. Opportunities for philanthropy arise. Gratitude is key. Cooperation leads to prosperity."},
  {"id":"p07","name":"Seven of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p07.png","message":"Patience is required today.","meaning":"Your efforts are beginning to show results. Evaluate progress carefully. Invest time wisely. Avoid rushing outcomes. Reflect on long-term goals. Perseverance leads to reward."},
  {"id":"p08","name":"Eight of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p08.png","message":"Skill development pays off.","meaning":"Dedication and practice improve mastery. Focus on craftsmanship or learning. Attention to detail matters. Seek excellence in your work. Rewards grow steadily. Commitment ensures success."},
  {"id":"p09","name":"Nine of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p09.png","message":"Enjoy self-sufficiency and comfort.","meaning":"Independence brings satisfaction. Material security is highlighted. Appreciate achievements. Take pride in accomplishments. Gratitude for what you have enhances joy. Personal growth is evident."},
  {"id":"p10","name":"Ten of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p10.png","message":"Family and legacy are emphasized.","meaning":"Long-term stability and prosperity appear. Focus on inheritance and legacy. Relationships within family matter. Generational guidance is beneficial. Celebrate success. Plan for sustainable growth."},
  {"id":"p11","name":"Page of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p11.png","message":"Curiosity leads to growth.","meaning":"Learning opportunities arise. Seek knowledge diligently. Explore new skills. Stay open-minded. Practical experiments are favored. Develop competence steadily."},
  {"id":"p12","name":"Queen of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p12.png","message":"Nurturing energy supports stability.","meaning":"Focus on home and financial stability. Practical wisdom guides decisions. Compassion and care enhance relationships. Be resourceful and grounded. Support others effectively. Balance personal and material needs."},
  {"id":"p13","name":"King of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p13.png","message":"Leadership in material matters shines.","meaning":"Confidence and authority in finances and career. Responsible management leads to success. Generosity is respected. Planning for long-term growth is highlighted. Mentor others wisely. Stay grounded in decisions."},
  {"id":"p14","name":"Knight of Pentacles","type":"Minor Arcana","suit":"Pentacles","image":"images/cards/p14.png","message":"Persistence ensures steady progress.","meaning":"Hard work pays off over time. Responsibility is key. Methodical approach benefits outcomes. Stay patient and committed. Practicality guides actions. Slow but steady wins today."},

  // Minor Arcana - Cups
  {"id":"c01","name":"Ace of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c01.png","message":"New emotional beginnings appear.","meaning":"Love, inspiration, or friendship starts anew. Embrace emotional openness. Express feelings clearly. Nurture relationships. Compassion and empathy flow. Opportunities for joy and connection emerge."},
  {"id":"c02","name":"Two of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c02.png","message":"Partnerships strengthen today.","meaning":"Harmonious connections are emphasized. Collaboration in relationships thrives. Mutual respect brings growth. Communication fosters understanding. Romantic bonds may deepen. Friendship and trust are highlighted."},
  {"id":"c03","name":"Three of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c03.png","message":"Celebrate and share joy.","meaning":"Friendship and community bring happiness. Social gatherings may occur. Cooperation and support are rewarding. Emotional fulfillment is present. Express gratitude and enjoy companionship. Positive experiences multiply."},
  {"id":"c04","name":"Four of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c04.png","message":"Reflection brings new insight.","meaning":"Contemplate emotional satisfaction. Consider new offers carefully. Avoid apathy. Seek clarity in relationships. Be mindful of emotional needs. Decisions require awareness and attention."},
  {"id":"c05","name":"Five of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c05.png","message":"Focus on what remains.","meaning":"Loss or disappointment may be present. Recognize what is still valuable. Embrace lessons learned. Avoid dwelling on regrets. Emotional recovery is important. Look for remaining opportunities."},
  {"id":"c06","name":"Six of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c06.png","message":"Nostalgia brings comfort.","meaning":"Reflect on happy memories. Emotional healing may occur. Reconnect with past joy. Relationships with childhood or past figures highlighted. Appreciate simple pleasures. Fondness for tradition enriches the day."},
  {"id":"c07","name":"Seven of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c07.png","message":"Choices may confuse—focus carefully.","meaning":"Multiple options appear. Distinguish illusion from reality. Prioritize wisely. Avoid overindulgence in fantasies. Decisions require clarity. Mindfulness guides the best choice."},
  {"id":"c08","name":"Eight of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c08.png","message":"Move toward higher purpose.","meaning":"Leave dissatisfaction behind. Emotional growth requires change. Seek meaningful goals. Personal development is highlighted. Let go of what no longer serves. Pursue deeper understanding and fulfillment."},
  {"id":"c09","name":"Nine of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c09.png","message":"Wishes and contentment arrive.","meaning":"Emotional satisfaction is achievable. Gratitude enhances joy. Celebrate accomplishments. Share happiness with others. Appreciate personal success. Fulfillment in personal relationships highlighted."},
  {"id":"c10","name":"Ten of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c10.png","message":"Harmony in family and love.","meaning":"Joyful home life. Emotional fulfillment in relationships. Shared happiness strengthens bonds. Celebrate togetherness. Express appreciation. Alignment of values and love."},
  {"id":"c11","name":"Page of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c11.png","message":"Curiosity sparks emotional growth.","meaning":"Explore new feelings. Creative expression encouraged. Emotional curiosity leads to learning. Engage in artistic activities. Be open to messages from others. Playfulness enriches experiences."},
  {"id":"c12","name":"Queen of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c12.png","message":"Emotional intelligence guides you.","meaning":"Empathy and compassion influence actions. Nurture others wisely. Intuition informs decisions. Supportive presence is valuable. Calm and understanding resolve conflicts. Emotional insight is powerful today."},
  {"id":"c13","name":"King of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c13.png","message":"Balance emotions with wisdom.","meaning":"Control over feelings enables sound judgment. Emotional stability guides actions. Leadership with empathy is highlighted. Maintain calm in challenges. Support others wisely. Diplomacy ensures smooth interactions."},
  {"id":"c14","name":"Knight of Cups","type":"Minor Arcana","suit":"Cups","image":"images/cards/c14.png","message":"Romantic or emotional pursuit moves forward.","meaning":"Follow your heart with intention. Express emotions clearly. Opportunities for love may appear. Be creative in emotional matters. Seek meaningful connections. Pursue dreams with passion."},

  // Minor Arcana - Swords
  {"id":"s01","name":"Ace of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s01.png","message":"Clarity and insight arrive.","meaning":"New ideas emerge. Mental clarity allows decisions. Breakthroughs are possible. Focused action leads to success. Courage in communication matters. Truth and understanding guide you."},
  {"id":"s02","name":"Two of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s02.png","message":"Decision-making is crucial today.","meaning":"Weigh options carefully. Avoid impulsive choices. Balance logic and emotion. Seek compromise when needed. Trust your judgment. Consider all perspectives before acting."},
  {"id":"s03","name":"Three of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s03.png","message":"Emotional challenges may appear.","meaning":"Heartache or conflict arises. Accept feelings and learn. Communicate openly to resolve issues. Healing requires patience. Avoid dwelling on negativity. Insight comes through experience."},
  {"id":"s04","name":"Four of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s04.png","message":"Rest and reflection are necessary.","meaning":"Take a break to recover mentally. Solitude provides clarity. Recharge energy for future challenges. Avoid burnout. Contemplate solutions. Recovery enhances focus."},
  {"id":"s05","name":"Five of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s05.png","message":"Conflicts may arise—choose wisely.","meaning":"Tensions or disagreements possible. Avoid unnecessary battles. Stand firm but fair. Learn from confrontation. Consider long-term consequences. Strategy ensures success."},
  {"id":"s06","name":"Six of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s06.png","message":"Transition leads to calmer waters.","meaning":"Move away from difficulties. Journey toward clarity and peace. Adapt to change with grace. Solutions become clearer. Support is available. Progress through careful planning."},
  {"id":"s07","name":"Seven of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s07.png","message":"Be strategic and cautious today.","meaning":"Discretion is important. Avoid deception and dishonesty. Plan carefully. Protect personal interests. Observe and act wisely. Tactful maneuvering brings advantage."},
  {"id":"s08","name":"Eight of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s08.png","message":"Feeling restricted? Seek liberation.","meaning":"Obstacles may seem overwhelming. Recognize mental constraints. Take small steps to regain freedom. Empower yourself with clarity. Avoid fear-driven decisions. Courage leads to liberation."},
  {"id":"s09","name":"Nine of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s09.png","message":"Anxiety may challenge you.","meaning":"Worries and fears arise. Analyze concerns rationally. Seek support if needed. Avoid overthinking. Rest and reflection are crucial. Solutions appear with patience."},
  {"id":"s10","name":"Ten of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s10.png","message":"Endings bring release and new beginnings.","meaning":"Difficult situations conclude. Accept closure gracefully. Learn from endings. Recovery follows hardship. Opportunities for renewal arise. Transformation is possible."},
  {"id":"s11","name":"Page of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s11.png","message":"Curiosity fuels intellect.","meaning":"Observe and gather information. Communicate clearly. Learn from challenges. Stay alert and adaptable. Critical thinking aids decisions. Explore new ideas actively."},
  {"id":"s12","name":"Queen of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s12.png","message":"Sharp intellect guides decisions.","meaning":"Clarity and honesty are essential. Strategic thinking leads to success. Avoid emotional bias in choices. Communicate truthfully. Independence is highlighted. Insight aids problem-solving."},
  {"id":"s13","name":"King of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s13.png","message":"Authority and intellect lead the way.","meaning":"Rational decision-making is key. Leadership requires fairness. Knowledge and strategy empower actions. Logical approach solves issues. Justice and ethics matter. Use wisdom to guide others."},
  {"id":"s14","name":"Knight of Swords","type":"Minor Arcana","suit":"Swords","image":"images/cards/s14.png","message":"Action and ambition drive progress.","meaning":"Act decisively with focus. Pursue goals with determination. Avoid recklessness. Swift action leads to achievement. Communication is direct. Mental agility ensures success."},

  // Minor Arcana - Wands
  {"id":"w01","name":"Ace of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w01.png","message":"New inspiration ignites today.","meaning":"Creative energy flows. Initiate new projects. Take bold action. Passion fuels progress. Opportunities for growth appear. Confidence boosts performance."},
  {"id":"w02","name":"Two of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w02.png","message":"Plan and strategize for success.","meaning":"Consider options carefully. Long-term vision is highlighted. Take measured steps. Collaboration may be beneficial. Stay confident in planning. Preparation ensures achievement."},
  {"id":"w03","name":"Three of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w03.png","message":"Expansion and progress are evident.","meaning":"Opportunities for growth appear. Explore new territories or ideas. Patience rewards initiative. Anticipate future developments. Stay proactive. Optimism fuels advancement."},
  {"id":"w04","name":"Four of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w04.png","message":"Celebrate achievements and milestones.","meaning":"Community and relationships thrive. Recognize successes. Stability and joy are present. Social gatherings bring happiness. Share gratitude. Foundation for future growth strengthens."},
  {"id":"w05","name":"Five of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w05.png","message":"Competition or conflict arises.","meaning":"Challenges require flexibility. Healthy competition motivates growth. Avoid unnecessary arguments. Collaborate when possible. Assertiveness and tact help. Learn from disagreements."},
  {"id":"w06","name":"Six of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w06.png","message":"Recognition and victory are yours.","meaning":"Achievements are acknowledged. Confidence increases. Public recognition motivates. Leadership is highlighted. Celebrate success. Continue pursuing goals with determination."},
  {"id":"w07","name":"Seven of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w07.png","message":"Stand firm in your position.","meaning":"Defend beliefs and ideas. Challenges may test resolve. Courage is essential. Maintain focus. Persevere despite opposition. Strength comes from conviction."},
  {"id":"w08","name":"Eight of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w08.png","message":"Swift movement brings progress.","meaning":"Rapid developments occur. Opportunities arrive quickly. Be prepared to act. Communication and travel are highlighted. Focus ensures results. Momentum favors action."},
  {"id":"w09","name":"Nine of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w09.png","message":"Resilience is key today.","meaning":"Persistence in the face of adversity is vital. Defend achievements. Prepare for final challenges. Courage and vigilance matter. Stay determined. Strength comes from experience."},
  {"id":"w10","name":"Ten of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w10.png","message":"Burden may feel heavy—delegate wisely.","meaning":"Responsibilities may overwhelm. Prioritize tasks carefully. Seek help if needed. Avoid burnout. Focus on essential duties. Strategic planning lightens load."},
  {"id":"w11","name":"Page of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w11.png","message":"Enthusiasm and curiosity guide you.","meaning":"Explore new opportunities. Learn through experience. Creativity is highlighted. Take initiative in projects. Stay adventurous. Energy fuels progress."},
  {"id":"w12","name":"Queen of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w12.png","message":"Confidence and charisma shine.","meaning":"Leadership and passion inspire others. Be bold in creativity. Express personal vision clearly. Courage and warmth attract support. Stay determined. Positive energy enhances outcomes."},
  {"id":"w13","name":"King of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w13.png","message":"Visionary leadership guides success.","meaning":"Lead with confidence and clarity. Strategic thinking is key. Inspire and motivate others. Take calculated risks. Maintain integrity. Achieve goals with foresight."},
  {"id":"w14","name":"Knight of Wands","type":"Minor Arcana","suit":"Wands","image":"images/cards/w14.png","message":"Adventure and bold action await.","meaning":"Take dynamic action. Pursue goals energetically. Avoid recklessness. Embrace challenges. Excitement and opportunity appear. Confidence drives results."}
];


let cardOpen = false;
let currentCard = null;

function getRandomCard() {
  const index = Math.floor(Math.random() * cards.length);
  return cards[index];
}

document.addEventListener("DOMContentLoaded", () => {
  const cardImg = document.getElementById("tarot-card");
  const cardNameDiv = document.getElementById("card-name");
  const messageDiv = document.getElementById("message");
  const meaningDiv = document.getElementById("meaning");


  cardNameDiv.style.display = "none";
  messageDiv.style.display = "none";
  meaningDiv.style.display = "none";

  cardImg.addEventListener("click", () => {
    if (!cardOpen) {
      currentCard = getRandomCard();
      cardImg.src = currentCard.image;

      cardNameDiv.textContent = currentCard.name;
      cardNameDiv.style.display = "block";

      messageDiv.textContent = currentCard.message;
      messageDiv.style.display = "block";

      meaningDiv.innerHTML = `<p>${currentCard.meaning}</p>`;
      meaningDiv.style.display = "block";

      cardOpen = true;
    } else {
      cardImg.src = "images/cards/back.png";


      cardNameDiv.style.display = "none";
      messageDiv.style.display = "none";
      meaningDiv.style.display = "none";

      currentCard = null;
      cardOpen = false;
    }
  });

});
